spring:
  application:
    name: ms-auth

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:iticket_user}
    password: ${SPRING_DATASOURCE_PASSWORD:iticket_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret-key: Y2xhdWRlLWNvZGUtYm9vay1zZXJ2aWNlLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9u
  access-token-expiration: 15
  refresh-token-expiration: 1440

app:
  seed:
    admin:
      username: admin
      email: admin@iticket.com
      password: Admin@123!

server:
  port: 9091
